---
galaxy_info:
  role_name: "project_backup"
  namespace: "ebdruplab"
  author: "Kristian Ebdrup"
  description: "Backup Semaphore UI project via writen semaphoreui modules, to be used with project_deploy role"
  license: "MIT"
  min_ansible_version: "2.10"
  platforms:
    - name: "EL"
      versions:
        - "all"
    - name: "Debian"
      versions:
        - "all"
    - name: "Ubuntu"
      versions:
        - "all"
  galaxy_tags:
    - "semaphore"
    - "backup"
    - "ansible"
    - "devops"
dependencies: []
