namespace: ebdruplab
name: semaphoreui
version: 1.0.0
readme: README.md
authors:
  - Kristian Ebdrup <kristian@ebdruplab.dk>

description: An implementation that makes it easier to talk to semaphore UI API endpoints.
license:
  - MIT
# license_file: 'LICENSE'
tags:
  - semaphoreui
  - api_call
  - automation
  - devops
  - linux
  - infrastructure
dependencies: {}
repository: https://github.com/ebdruplab/ansible-collection_ebdruplab
documentation: https://github.com/ebdruplab/ansible-collection_ebdruplab
homepage: https://github.com/Ebdruplab/ansible-collection_ebdruplab/tree/main/ebdruplab/semaphoreui
issues: https://github.com/Ebdruplab/ansible-collection_ebdruplab/issues
build_ignore:
  - tools
  - setup.cfg
  - galaxy.yml.j2
  - template_galaxy.yml
  - '*.tar.gz'
  - 'test/*'
  - '.gitignore'
  - '*.zip'
