---
- name: Test creating a template and extracting raw task output
  hosts: localhost
  gather_facts: false
  vars:
    semaphore_host: "http://localhost"
    semaphore_port: 3000
    semaphore_username: "{{ lookup('env', 'ebdruplab_integration_test_USER') | default('admin', true) }}"
    semaphore_password: "{{ lookup('env', 'ebdruplab_integration_test_PW') | default('changeme', true) }}"

  tasks:
    - name: Log in to Semaphore
      ebdruplab.semaphoreui.login:
        host: "{{ semaphore_host }}"
        port: "{{ semaphore_port }}"
        username: "{{ semaphore_username }}"
        password: "{{ semaphore_password }}"
      register: login_result

    - name: Create a project for testing
      ebdruplab.semaphoreui.project_create:
        host: "{{ semaphore_host }}"
        port: "{{ semaphore_port }}"
        session_cookie: "{{ login_result.session_cookie }}"
        name: "Template Output Project"
      register: created_project

    - name: Create dummy inventory
      ebdruplab.semaphoreui.project_inventory_create:
        host: "{{ semaphore_host }}"
        port: "{{ semaphore_port }}"
        session_cookie: "{{ login_result.session_cookie }}"
        project_id: "{{ created_project.project.id }}"
        inventory:
          name: "Integration Test Inventory"
          type: static
          inventory: "localhost ansible_connection=local"
      register: created_inventory

    - name: Create dummy SSH key
      ebdruplab.semaphoreui.project_key_create:
        host: "{{ semaphore_host }}"
        port: "{{ semaphore_port }}"
        session_cookie: "{{ login_result.session_cookie }}"
        project_id: "{{ created_project.project.id }}"
        name: "Dummy Key"
        type: ssh
        ssh:
          login: git
          private_key: "dummy-private-key"
      register: created_key

    - name: Create dummy repository
      ebdruplab.semaphoreui.project_repository_create:
        host: "{{ semaphore_host }}"
        port: "{{ semaphore_port }}"
        session_cookie: "{{ login_result.session_cookie }}"
        project_id: "{{ created_project.project.id }}"
        repository:
          name: "Dummy Repo"
          git_url: "https://github.com/example/repo.git"
          git_branch: "main"
          ssh_key_id: "{{ created_key.key.id }}"
      register: created_repo

    - name: Create dummy view
      ebdruplab.semaphoreui.project_view_create:
        host: "{{ semaphore_host }}"
        port: "{{ semaphore_port }}"
        session_cookie: "{{ login_result.session_cookie }}"
        project_id: "{{ created_project.project.id }}"
        title: "Test View"
        position: 1
      register: created_view

    - name: Create a dummy template in project
      ebdruplab.semaphoreui.project_template_create:
        host: "{{ semaphore_host }}"
        port: "{{ semaphore_port }}"
        session_cookie: "{{ login_result.session_cookie }}"
        project_id: "{{ created_project.project.id }}"
        template:
          name: "Integration Template"
          app: "ansible"
          playbook: "site.yml"
          git_branch: "main"
          inventory_id: "{{ created_inventory.inventory.id | int }}"
          repository_id: "{{ created_repo.repository.id | int }}"
          view_id: "{{ created_view.view.id | int }}"
          type: "job"
          allow_override_args_in_task: false
          survey_vars: []

    - name: Wait for any tasks to trigger (optional)
      pause:
        seconds: 2

    - name: Get list of tasks for the project
      ebdruplab.semaphoreui.project_task_list:
        host: "{{ semaphore_host }}"
        port: "{{ semaphore_port }}"
        session_cookie: "{{ login_result.session_cookie }}"
        project_id: "{{ created_project.project.id }}"
      register: project_tasks

    - name: Ensure at least one task exists
      assert:
        that:
          - project_tasks.tasks | length > 0

    - name: Get latest task ID
      set_fact:
        latest_task_id: "{{ (project_tasks.tasks | sort(attribute='start') | last).id }}"

    - name: Fetch raw output of the latest task
      ebdruplab.semaphoreui.project_task_raw_output:
        host: "{{ semaphore_host }}"
        port: "{{ semaphore_port }}"
        session_cookie: "{{ login_result.session_cookie }}"
        project_id: "{{ created_project.project.id }}"
        task_id: "{{ latest_task_id }}"
      register: raw_output

    - name: Show task raw output
      debug:
        var: raw_output.raw_output

    - name: Log out
      ebdruplab.semaphoreui.logout:
        host: "{{ semaphore_host }}"
        port: "{{ semaphore_port }}"
        session_cookie: "{{ login_result.session_cookie }}"
