# roles/project_backup/tasks/main.yml
---
- name: "Resolve | Globals"
  ansible.builtin.include_tasks:
    file: "resolve_global.yml"
  tags:
    - resolve
    - auth

- name: "Resolve | Globals"
  ansible.builtin.include_tasks:
    file: "assert.yml"
  tags:
    - assert

- name: "Auth | Login"
  ansible.builtin.include_tasks:
    file: "login.yml"
  tags:
    - auth
    - login

- name: "Proceed with project backup"
  block:

    - name: "Backup | Ensure output dir"
      ansible.builtin.include_tasks:
        file: "output.yml"
      tags:
        - output

    - name: "Backup | Resolve project"
      ansible.builtin.include_tasks:
        file: "resolve_project.yml"
      tags:
        - project

    - name: "Backup | Fetch project data"
      ansible.builtin.include_tasks:
        file: "fetch.yml"
      tags:
        - project
        - list
        - get

    - name: "Backup | Normalize"
      ansible.builtin.include_tasks:
        file: "normalize.yml"
      tags:
        - normalize

    - name: "Backup | Build config"
      ansible.builtin.include_tasks:
        file: "build.yml"
      tags:
        - build

    - name: "Backup | Write vars file"
      ansible.builtin.include_tasks:
        file: "write.yml"
      tags:
        - output

  always:
    - name: "Auth | Logout"
      ansible.builtin.include_tasks:
        file: "logout.yml"
      tags:
        - auth
        - logout
