---
- name: "Output | Write raw backup JSON file"
  ansible.builtin.copy:
    dest: "{{ project_backup_output_dir }}/{{ project_backup_json_filename }}"
    content: "{{ _project_backup_export_obj | to_nice_json }}"
    mode: "0600"
  no_log: "{{ project_backup_sensitive_data_no_log }}"
  tags:
    - output
    - project_backup

