---

- name: "Create project environments"
  ebdruplab.semaphoreui.project_environment_create:
    host: "{{ project_deploy_semaphore_host }}"
    port: "{{ project_deploy_semaphore_port }}"
    session_cookie: "{{ login_result.session_cookie }}"
    project_id: "{{ current_project_id }}"
    environment:
      name: "{{ item.name }}"
      password: "{{ item.password | default(omit) }}"
      env: "{{ item.env | default(omit) }}"
      json: "{{ item.json | default(omit) }}"
      extra_variables: "{{ item.extra_variables | default(omit) }}"
      secrets: "{{ item.secrets | default(omit) }}"
  loop: "{{ project_deploy_config.environments | default({}) | dict2items | map(attribute='value') | list }}"
  loop_control:
    label: "{{ item.name }}"
  register: created_environments_result
  no_log: "{{ project_deploy_sensitive_data_no_log | default(true) | bool }}"

- name: "Set created environments fact"
  ansible.builtin.set_fact:
    created_environments_by_name: "{{ created_environments_by_name | default({}) | combine({ (item.environment.name): item.environment }) }}"
  loop: "{{ created_environments_result.results | default([]) }}"
  loop_control:
    label: "{{ item.environment.name | default('unknown') }}"
  when: item.environment is defined
