- name: Create inventories
  ebdruplab.semaphoreui.project_inventory_create:
    host: "{{ project_deploy_semaphore_host }}"
    port: "{{ project_deploy_semaphore_port }}"
    session_cookie: "{{ project_deploy_login_result.session_cookie }}"
    project_id: "{{ current_project_id }}"
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    inventory: "{{ item.inventory }}"
  loop: "{{ project_item.inventories }}"
  loop_control:
    label: "{{ item.name }}"
