#SPDX-License-Identifier: MIT-0
---
# tasks file for ebdruplab.semaphoreui.project_deploy

- name: "Resolve | Apply ebdruplab_* globals to project_deploy_* when any global is set"
  ansible.builtin.set_fact:
    project_deploy_semaphore_host: "{{ project_deploy_semaphore_host | default(ebdruplab_semaphore_host | default('http://localhost')) }}"
    project_deploy_semaphore_port: "{{ project_deploy_semaphore_port | default(ebdruplab_semaphore_port | default(3000)) }}"
    project_deploy_semaphore_username: "{{ project_deploy_semaphore_username | default(ebdruplab_semaphore_username | default('')) }}"
    project_deploy_semaphore_password: "{{ project_deploy_semaphore_password | default(ebdruplab_semaphore_password | default('')) }}"
    project_deploy_semaphore_api_token: "{{ project_deploy_semaphore_api_token | default(ebdruplab_semaphore_api_token | default(omit)) }}"
  no_log: "{{ project_deploy_sensitive_data_no_log | default(true) }}"
  when:
    - ebdruplab_semaphore_host is defined
      or ebdruplab_semaphore_port is defined
      or ebdruplab_semaphore_username is defined
      or ebdruplab_semaphore_password is defined
      or ebdruplab_semaphore_api_token is defined
  tags:
    - resolve
    - auth

- name: "Include assert tasks"
  ansible.builtin.include_tasks:
    file: assert.yml

- name: "Include Login to Semaphoreui"
  ansible.builtin.include_tasks:
    file: login.yml
  when: project_deploy_semaphore_api_token is not defined

- name: "Include project_preflight tasks"
  ansible.builtin.include_tasks:
    file: project_preflight.yml

- name: "Proeced with project deployment and creation of ressources"
  block:

    - name: "Include project file"
      ansible.builtin.include_tasks:
        file: project.yml

    - name: "Include project file"
      ansible.builtin.include_tasks:
        file: project_user.yml

    - name: "Include keys file"
      ansible.builtin.include_tasks:
        file: keys.yml

    - name: "Include repositories file"
      ansible.builtin.include_tasks:
        file: repositories.yml

    - name: "Include views file"
      ansible.builtin.include_tasks:
        file: views.yml

    - name: "Include inventories file"
      ansible.builtin.include_tasks:
        file: inventories.yml

    - name: "Include environments file"
      ansible.builtin.include_tasks:
        file: environments.yml

    - name: "Include templates file"
      ansible.builtin.include_tasks:
        file: templates.yml

    - name: "Include schedules file"
      ansible.builtin.include_tasks:
        file: schedules.yml

    - name: "Include integrations file"
      ansible.builtin.include_tasks:
        file: integrations.yml
  always:

    - name: "Include Logout to Semaphoreui"
      ansible.builtin.include_tasks:
        file: logout.yml
      when: project_deploy_semaphore_api_token is not defined
