---
- name: "Create project template {{ item.name }}"
  ebdruplab.semaphoreui.project_template_create:
    host: "{{ project_deploy_semaphore_host }}"
    port: "{{ project_deploy_semaphore_port }}"
    api_token: "{{ project_deploy_semaphore_api_token | default(omit) }}"
    session_cookie: "{{ login_result.session_cookie | default(omit) }}"
    project_id: "{{ current_project_id }}"
    template:
      name: "{{ item.name }}"
      app: "{{ item.app | default('ansible') }}"
      playbook: "{{ item.playbook }}"
      inventory_id: >-
        {{ (created_inventory_by_name[item.inventory_name].id | int)
           if (item.inventory_name is defined and item.inventory_name in created_inventory_by_name)
           else omit }}
      repository_id: >-
        {{ created_repos_by_name[item.repository_name].id | int }}
      environment_id: >-
        {{ (created_environments_by_name[item.environment_name].id | int)
           if (item.environment_name is defined
               and item.environment_name|length > 0
               and item.environment_name in created_environments_by_name)
           else omit }}
      view_id: >-
        {{ (created_project_view_by_title[item.view_title].id | int)
           if (item.view_title is defined
               and item.view_title in created_project_view_by_title)
           else omit }}
      type: "{{ item.type }}"
      description: "{{ item.description | default('') }}"
      vaults: "{{ item.vaults | default(omit, true) }}"
      arguments: "{{ item.arguments | default(omit, true) }}"
  loop: "{{ project_deploy_config.templates.values() }}"
  loop_control:
    label: "{{ item.name }}"
  register: created_templates_result

- name: "Set created templates fact"
  ansible.builtin.set_fact:
    created_templates_by_name: "{{ created_templates_by_name | default({}) | combine({ item.item.name: item.template }) }}"
  loop: "{{ created_templates_result.results | default([]) }}"
  loop_control:
    label: "{{ item.item.name | default('unknown') }}"
  when: item.template is defined

- name: "Debug task (template)"
  ansible.builtin.debug:
    var: created_templates_by_name
  when: project_deploy_debug
